"""Build the companion website: a static page with the paper's interactive figures.

    python scripts/build_site.py                 # full site from the current outputs
    python scripts/build_site.py --placeholder   # landing page only, so the URL resolves

Writes `site/` (git-ignored).  Deploy it by pushing its contents to the `gh-pages` branch;
the CNAME file maps it to the custom domain.  Plotly is loaded from its CDN, so pages stay
small: points are subsampled, and every figure is a few hundred kB of JSON.
"""
from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
REPRO = ROOT / "scripts" / "reproductions" / "promise_of_contrast"
sys.path[:0] = [str(ROOT), str(REPRO)]

SITE = {
    "title": "Probing Without Labels",
    "subtitle": "Contrast-only Reproductions of Interpretability Results",
    "authors": ["Stefan F. Schouten", "Peter Bloem"],
    "affiliation": "Vrije Universiteit Amsterdam",
    "venue": "BlackboxNLP 2026",
    "domain": "contrast.stefanfs.me",
    "links": [("Code", "https://github.com/sfschouten/promise_of_contrast"),
              ("Paper", None)],          # ACL Anthology link once it exists
}
MODELS = {"llama2_7b": "Llama-2-7B", "llama3_8b": "Llama-3.1-8B"}
BASES = {"generalized_cross_covariance_8": "g-tcPCA", "cross_covariance_8": "tcPCA"}
MAX_POINTS = 350          # per class, per figure
OUT = ROOT / "site"

CSS = """
:root { --bg:#fbfaf7; --fg:#1d1d1f; --muted:#5f6368; --line:#e3e1dc; --card:#ffffff; --accent:#1b6ca8; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#141414; --fg:#ececec; --muted:#a0a0a0; --line:#2c2c2c; --card:#1c1c1c; --accent:#7fb8e6; } }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font: 16px/1.55 "Iowan Old Style", "Palatino Linotype", Georgia, serif; }
main { max-width: 1080px; margin: 0 auto; padding: 48px 20px 80px; }
header { border-bottom: 1px solid var(--line); padding-bottom: 28px; margin-bottom: 36px; }
h1 { font-size: 2.3rem; line-height: 1.15; margin: 0 0 6px; letter-spacing: -0.01em; }
.sub { font-size: 1.25rem; color: var(--muted); margin: 0 0 18px; }
.meta { font: 14px/1.5 system-ui, sans-serif; color: var(--muted); }
.links a, .links span { font: 600 14px system-ui, sans-serif; margin-right: 18px; color: var(--accent);
       text-decoration: none; border-bottom: 1px solid transparent; }
.links a:hover { border-bottom-color: var(--accent); }
.links span { color: var(--muted); font-weight: 400; }
h2 { font-size: 1.45rem; margin: 44px 0 6px; }
p.lede { color: var(--muted); max-width: 760px; margin: 0 0 18px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(460px, 100%), 1fr)); gap: 18px; }
.card { min-width: 0; overflow: hidden; background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 10px 10px 4px; }
.card .plotly-graph-div { width: 100% !important; }
.card h3 { font: 600 13px system-ui, sans-serif; margin: 4px 6px 0; color: var(--muted);
           text-transform: uppercase; letter-spacing: .04em; }
.sel { display: flex; flex-wrap: wrap; gap: 16px; margin: 8px 6px 0; font: 13px system-ui, sans-serif;
       color: var(--muted); }
.sel select { font: inherit; color: var(--fg); background: var(--card); border: 1px solid var(--line);
              border-radius: 6px; padding: 3px 6px; margin-left: 6px; }
.soon { font: 15px system-ui, sans-serif; color: var(--muted); padding: 28px; border: 1px dashed var(--line);
        border-radius: 10px; text-align: center; }
footer { margin-top: 64px; font: 13px system-ui, sans-serif; color: var(--muted); }
"""


def _header() -> str:
    links = " ".join(f'<a href="{html.escape(u)}">{html.escape(t)}</a>' if u
                     else f"<span>{html.escape(t)} (soon)</span>" for t, u in SITE["links"])
    return f"""<header>
  <h1>{html.escape(SITE['title'])}</h1>
  <p class="sub">{html.escape(SITE['subtitle'])}</p>
  <p class="meta">{', '.join(map(html.escape, SITE['authors']))} · {html.escape(SITE['affiliation'])}
  · {html.escape(SITE['venue'])}</p>
  <p class="links">{links}</p>
</header>"""


def _page(body: str) -> str:
    from plotly.offline import get_plotlyjs_version
    PLOTLY_JS = get_plotlyjs_version()
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(SITE['title'])}: {html.escape(SITE['subtitle'])}</title>
<style>{CSS}</style></head>
<body><main>
{_header()}
{body}
<footer>Figures are generated by the paper's code; see the repository to rebuild them.</footer>
<script src="https://cdn.plot.ly/plotly-{PLOTLY_JS}.min.js"></script>
<script>
// Draw every figure once the layout is final, so each is sized against its own card.
document.querySelectorAll(".plot").forEach(function (d) {{
  var f = JSON.parse(document.getElementById(d.id + "-json").textContent);
  Plotly.newPlot(d, f.data, f.layout, {{displaylogo: false, responsive: true,
                                        modeBarButtonsToRemove: ["select2d", "lasso2d"]}});
  // Dataset and token selects (see _selector): show the one group of traces they pick.
  var s = f.layout.meta && f.layout.meta.selector;
  if (!s) return;
  var box = d.parentNode.querySelector(".sel");
  function pick() {{
    var g = box.querySelector('[data-dim="tok"]').selectedIndex * s.datasets.length
          + box.querySelector('[data-dim="ds"]').selectedIndex;
    var vis = f.data.map(function (_, i) {{ return Math.floor(i / s.per_group) === g; }});
    Plotly.restyle(d, {{visible: vis}});
  }}
  box.querySelectorAll("select").forEach(function (e) {{ e.addEventListener("change", pick); }});
}});
</script>
</main></body></html>
"""


def _subsample(n: int, k: int, seed: int = 0) -> np.ndarray:
    return np.random.default_rng(seed).choice(n, size=min(n, k), replace=False)


def tetrahedron_figure(model: str, method: str):
    import plotly.graph_objects as go
    from tetrahedron import opposite_edge_pairings, overview_view, view_axis
    from tetrahedron_figure import NODE_COLORS, NODE_LABELS, NODES, _contrast_name, projected_points

    coords, nodes = projected_points(model, 15, method)
    means = {k: coords[nodes == k].mean(axis=0) for k in NODES}
    comp = BASES[method]
    fig = go.Figure()
    for k in NODES:
        pts = coords[nodes == k]
        pts = pts[_subsample(len(pts), MAX_POINTS)]
        fig.add_trace(go.Scatter3d(x=pts[:, 0], y=pts[:, 1], z=pts[:, 2], mode="markers",
                                   marker=dict(size=2, color=NODE_COLORS[k], opacity=0.45),
                                   name=f"{k}: {NODE_LABELS[k].strip()}", hoverinfo="skip"))
    edges = [(a, b) for i, a in enumerate(NODES) for b in NODES[i + 1:]]
    xs, ys, zs = [], [], []
    for a, b in edges:
        for p in (means[a], means[b]):
            xs.append(p[0]); ys.append(p[1]); zs.append(p[2])
        xs.append(None); ys.append(None); zs.append(None)
    fig.add_trace(go.Scatter3d(x=xs, y=ys, z=zs, mode="lines", line=dict(color="#555", width=3),
                               showlegend=False, hoverinfo="skip"))
    m = np.stack([means[k] for k in NODES])
    fig.add_trace(go.Scatter3d(x=m[:, 0], y=m[:, 1], z=m[:, 2], mode="markers+text", text=NODES,
                               textposition="top center", showlegend=False,
                               marker=dict(size=7, symbol="diamond", color=[NODE_COLORS[k] for k in NODES],
                                           line=dict(color="#222", width=1))))

    def eye(v):
        # Keep the camera above the scene: plotly's turntable spins about the vertical axis,
        # so from below every drag feels reversed.  Looking along -v shows the same
        # orthographic projection, mirrored, so the view keeps its meaning.
        v = np.asarray(v, float)
        if v[2] < 0:
            v = -v
        v = v / np.linalg.norm(v) * 2.0
        return dict(eye=dict(x=v[0], y=v[1], z=v[2]), up=dict(x=0, y=0, z=1),
                    projection=dict(type="orthographic"))

    views = [("oblique", overview_view(means))]
    views += [(f"depth is {_contrast_name(p)}", view_axis(means, p)) for p in opposite_edge_pairings(NODES)]
    buttons = [dict(label=name, method="relayout", args=[{"scene.camera": eye(v)}]) for name, v in views]
    fig.update_layout(
        height=540, margin=dict(l=0, r=0, t=56, b=0), paper_bgcolor="rgba(0,0,0,0)",
        modebar=dict(orientation="v"),
        legend=dict(orientation="h", y=-0.02, font=dict(size=11)),
        scene=dict(aspectmode="data", camera=eye(views[0][1]),
                   xaxis_title=f"{comp} 1", yaxis_title=f"{comp} 2", zaxis_title=f"{comp} 3"),
        updatemenus=[dict(type="buttons", direction="right", x=0.0, y=1.0, xanchor="left",
                          yanchor="bottom", pad=dict(t=4, b=4),
                          buttons=buttons, showactive=True, **MENU_STYLE)])
    return fig


# Plotly's menus default to a see-through background, so an open dropdown lay over the
# plot and was hard to read.  Opaque and light, it reads on both the light and dark page.
MENU_STYLE = dict(bgcolor="#ffffff", bordercolor="#b8b6b0", borderwidth=1,
                  font=dict(size=11, color="#1d1d1f"))


def _layer(model: str, key: str, method: str, default: int = 15) -> int:
    """The layer the paper's figure uses: picked by the non-binary sweep in reproduce.py."""
    import csv
    path = REPRO.parents[2] / "outputs" / "reproductions" / "promise_of_contrast" / model / "nonbinary_layers_chosen.csv"
    if path.exists():
        for row in csv.DictReader(path.open()):
            if row["figure"] == key and row["basis"] == BASES[method]:
                return int(row["layer"])
    return default


def plane_figure(model: str, key: str, method: str):
    import plotly.graph_objects as go
    import panels

    spec = panels.PANELS[key]
    coords, labels, _ = panels._project(model, spec, method, _layer(model, key, method), "last")
    order = [o for o in spec["order"] if o in set(labels)]
    if spec["cmap"]:
        import matplotlib.pyplot as plt
        from matplotlib.colors import to_hex
        cmap = plt.get_cmap(spec["cmap"])
        colours = {o: to_hex(cmap(i / len(order))) for i, o in enumerate(order)}
    else:
        colours = panels.TRUTH_COLOURS
    fig = go.Figure()
    for o in order:
        pts = coords[labels == o]
        pts = pts[_subsample(len(pts), MAX_POINTS)]
        fig.add_trace(go.Scatter(x=pts[:, 0], y=pts[:, 1], mode="markers", name=o,
                                 marker=dict(size=4, color=colours[o], opacity=0.5)))
    # Class centroids, joined in order and closed: a loop for the calendar features, the
    # true / false / neither triangle for the trinary one.
    if order:
        cyc = np.stack([coords[labels == o].mean(0) for o in order] + [coords[labels == order[0]].mean(0)])
        fig.add_trace(go.Scatter(x=cyc[:, 0], y=cyc[:, 1], mode="lines+markers", showlegend=False,
                                 line=dict(color="#555", width=1.5),
                                 marker=dict(size=9, symbol="diamond",
                                             color=[colours[o] for o in order] + [colours[order[0]]])))
    comp = BASES[method]
    fig.update_layout(height=420, margin=dict(l=40, r=10, t=10, b=40), paper_bgcolor="rgba(0,0,0,0)",
                      modebar=dict(orientation="v"),
                      plot_bgcolor="rgba(0,0,0,0)", xaxis_title=f"{comp} 1", yaxis_title=f"{comp} 2",
                      legend=dict(font=dict(size=10)))
    return fig


OUTPUTS = REPRO.parents[2] / "outputs" / "reproductions" / "promise_of_contrast"
DATASETS = ["comparisons", "sp_en_trans", "cities", "amazon", "imdb", "ent_bank", "snli", "copa", "rte"]
TOKEN = {"second_to_last": "answer", "last": "period", "answer": "answer", "period": "period"}


def _selector(fig, tokens: tuple[str, ...], datasets: list[str], per_group: int):
    """Show one (token, dataset) group of `per_group` traces at a time.

    Traces must be added token-major.  Two plotly menus can't see each other's state, so the
    choice is made with two HTML selects instead: `card` renders them from this metadata and
    the page script restyles the plot's visibility (see _page).
    """
    fig.update_layout(meta=dict(selector=dict(tokens=list(tokens), datasets=list(datasets),
                                              per_group=per_group)))


def layer_sweep_figure(model: str):
    """Accuracy against layer for every dataset and token, one at a time."""
    import pandas as pd
    import plotly.graph_objects as go

    df = pd.read_csv(OUTPUTS / model / "layer_sweep.csv")
    df["token"] = df["position"].map(TOKEN)
    style = {"tcPCA-1": ("tcPCA", "#1f77b4"), "GCC-1": ("g-tcPCA", "#9467bd"),
             "logistic": ("logistic (supervised)", "#7f7f7f"), "CCS": ("CCS (median of 5 seeds)", "#d62728")}
    fig, groups = go.Figure(), []
    for token in ("answer", "period"):
        for ds in DATASETS:
            at = df[(df["dataset"] == ds) & (df["token"] == token)]
            groups.append(f"{ds} · {token}")
            for method, (lab, col) in style.items():
                c = at[at["method"] == method].groupby("layer")["acc"].median()
                fig.add_trace(go.Scatter(x=c.index, y=c.values, mode="lines+markers", name=lab,
                                         line=dict(color=col, dash="dot" if method == "logistic" else None),
                                         marker=dict(size=5), visible=not groups[1:]))
    _selector(fig, ("answer", "period"), DATASETS, len(style))
    fig.add_vline(x=15, line=dict(color="#aaa", dash="dash"))
    fig.update_layout(height=400, margin=dict(l=50, r=10, t=24, b=40), paper_bgcolor="rgba(0,0,0,0)",
                      plot_bgcolor="rgba(0,0,0,0)", yaxis=dict(range=[0.35, 1.02], title="accuracy"),
                      xaxis=dict(title="layer (decoder block)"),
                      legend=dict(orientation="h", y=-0.28, font=dict(size=10)))
    return fig


def spectra_figure(model: str):
    """Top tcPCA eigenvalues for every dataset and token, one at a time."""
    import pandas as pd
    import plotly.graph_objects as go

    df = pd.read_csv(OUTPUTS / model / "eigenvalues.csv")
    df = df[df["basis"] == "tcPCA-8"]
    fig, groups = go.Figure(), []
    for token in ("answer", "period"):
        for ds in DATASETS:
            at = df[(df["dataset"] == ds) & (df["position"] == token)].sort_values("index")
            groups.append(f"{ds} · {token}")
            fig.add_trace(go.Bar(x=[f"λ{j}" for j in at["index"]], y=at["eigenvalue"],
                                 marker_color="#1f77b4", visible=not groups[1:], showlegend=False))
    _selector(fig, ("answer", "period"), DATASETS, 1)
    fig.update_layout(height=320, margin=dict(l=40, r=10, t=24, b=30), paper_bgcolor="rgba(0,0,0,0)",
                      plot_bgcolor="rgba(0,0,0,0)", yaxis_title="eigenvalue")
    return fig


def seed_figure(model: str):
    """Every CCS seed's accuracy, per dataset and token."""
    import pandas as pd
    import plotly.graph_objects as go

    df = pd.read_csv(OUTPUTS / model / "ccs_seed_accuracy.csv")
    fig = go.Figure()
    for token, col in (("answer", "#1f77b4"), ("period", "#d62728")):
        at = df[df["position"] == token]
        fig.add_trace(go.Box(x=at["dataset"], y=at["acc"], name=token, boxpoints="all", jitter=0.5,
                             pointpos=0, marker=dict(color=col, size=4, opacity=0.6),
                             line=dict(width=0), fillcolor="rgba(0,0,0,0)"))
    fig.update_layout(boxmode="group", height=380, margin=dict(l=40, r=10, t=10, b=60),
                      paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                      yaxis=dict(range=[0, 1.02], title="accuracy per seed"),
                      xaxis=dict(categoryorder="array", categoryarray=DATASETS))
    return fig


def build(placeholder: bool) -> None:
    OUT.mkdir(exist_ok=True)
    (OUT / "CNAME").write_text(SITE["domain"] + "\n")
    (OUT / ".nojekyll").write_text("")
    if placeholder:
        body = ('<p class="lede">Companion site for the paper. The interactive figures '
                '(the negation × truth tetrahedron, true/false/neither, days and months) '
                'will appear here shortly.</p><div class="soon">Interactive figures coming soon.</div>')
        (OUT / "index.html").write_text(_page(body))
        return

    count = [0]

    def card(title: str, fig) -> str:
        # Figures are drawn only after the page is laid out (see _page), so each one is
        # sized against its final card instead of whatever the grid held mid-parse.
        count[0] += 1
        pid = f"plot{count[0]}"
        spec = fig.to_json().replace("</", "<\\/")
        meta = fig.layout.meta
        sel = meta.get("selector") if isinstance(meta, dict) else None
        controls = ""
        if sel:
            def select(label: str, dim: str, options: list[str]) -> str:
                opts = "".join(f"<option>{html.escape(o)}</option>" for o in options)
                return f'<label>{label}<select data-dim="{dim}">{opts}</select></label>'
            controls = ('<div class="sel">' + select("dataset", "ds", sel["datasets"])
                        + select("token", "tok", sel["tokens"]) + "</div>")
        return (f'<div class="card"><h3>{html.escape(title)}</h3>{controls}'
                f'<div class="plot" id="{pid}" style="height:{fig.layout.height}px"></div>'
                f'<script type="application/json" id="{pid}-json">{spec}</script></div>')

    sections = []
    cards = []
    for model, mname in MODELS.items():
        for method, bname in BASES.items():
            try:
                cards.append(card(f"{mname} · {bname}", tetrahedron_figure(model, method)))
            except LookupError as exc:
                print(f"  tetrahedron {model}/{bname}: skipped ({exc})")
    sections.append(("Negation and truth",
                     "Four statements per city: affirmed or negated, with the correct or an incorrect "
                     "country. On the first three components the four statement types form a "
                     "tetrahedron. Drag to rotate; the buttons look down the axis that collapses "
                     "one contrast.", cards))
    for key, title, lede in (
            ("trinary", "True, false, neither", "Statements about real cities (true or false) "
             "and invented ones (neither), on the first two components."),
            ("days_of_week", "Days of the week", "Tuples that differ only in the weekday; "
             "the class means are joined in calendar order."),
            ("months_of_year", "Months of the year", "Tuples that differ only in the month.")):
        cards = []
        for model, mname in MODELS.items():
            for method, bname in BASES.items():
                try:
                    cards.append(card(f"{mname} · {bname}", plane_figure(model, key, method)))
                except (LookupError, KeyError) as exc:
                    print(f"  {key} {model}/{bname}: skipped ({exc})")
        sections.append((title, lede, cards))

    for title, lede, make in (
            ("Choice of layer", "Accuracy against layer for tcPCA, g-tcPCA, CCS and a supervised logistic "
             "probe, per dataset and token (choose them above the plot). The paper summarises these as an "
             "average over datasets; block 15 (the paper's layer 16) sits on the plateau.", layer_sweep_figure),
            ("Eigenvalue spectra", "The top ten tcPCA eigenvalues per dataset and token. One eigenvalue "
             "standing out means the pairs isolate a single contrastive direction.", spectra_figure),
            ("CCS accuracy per seed", "Every one of the 30 CCS seeds, per dataset and token. Where the "
             "seeds split into two groups, a mean describes no run that actually happened.", seed_figure)):
        cards = []
        for model, mname in MODELS.items():
            try:
                cards.append(card(mname, make(model)))
            except FileNotFoundError as exc:
                print(f"  {title} {model}: skipped ({exc})")
        sections.append((title, lede, cards))

    body = "\n".join(f'<section><h2>{html.escape(t)}</h2><p class="lede">{html.escape(l)}</p>'
                     f'<div class="grid">{"".join(c)}</div></section>' for t, l, c in sections if c)
    (OUT / "index.html").write_text(_page(body))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--placeholder", action="store_true")
    args = parser.parse_args()
    build(args.placeholder)
    size = sum(f.stat().st_size for f in OUT.iterdir() if f.is_file())
    print(f"wrote {OUT} ({size / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
